"""empty message

Revision ID: a732bcef5842
Revises: 
Create Date: 2022-11-09 11:37:44.797578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a732bcef5842'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=45), nullable=False),
    sa.Column('city', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=False),
    sa.Column('userStatus', sa.Enum('regular', 'premium'), nullable=False),
    sa.Column('fk_location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id', 'fk_location_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('localad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('fk_category', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', 'confirmed'), nullable=False),
    sa.Column('publishingDate', sa.DateTime(), nullable=False),
    sa.Column('about', sa.String(length=45), nullable=True),
    sa.Column('photoUrls', sa.LargeBinary(), nullable=True),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.Column('fk_location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['fk_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'fk_category', 'fk_user_id', 'fk_location_id')
    )
    op.create_table('publicad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('fk_category', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', 'confirmed'), nullable=False),
    sa.Column('publishingDate', sa.DateTime(), nullable=False),
    sa.Column('about', sa.String(length=45), nullable=True),
    sa.Column('photoUrls', sa.LargeBinary(), nullable=True),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'fk_category', 'fk_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicad')
    op.drop_table('localad')
    op.drop_table('user')
    op.drop_table('location')
    op.drop_table('category')
    # ### end Alembic commands ###
