"""First migration


Revision ID: e366888bd6a1
Revises: 
Create Date: 2023-04-09 23:06:40.556598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e366888bd6a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=45), nullable=False),
    sa.Column('city', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=False),
    sa.Column('userStatus', sa.Enum('regular', 'premium'), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.Column('idlocation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idlocation'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id', 'idlocation'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('localad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', 'confirmed'), nullable=False),
    sa.Column('publishingDate', sa.DateTime(), nullable=False),
    sa.Column('about', sa.String(length=45), nullable=True),
    sa.Column('photoUrl', sa.String(length=10000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_category', 'user_id', 'location_id')
    )
    op.create_table('publicad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', 'confirmed'), nullable=False),
    sa.Column('publishingDate', sa.DateTime(), nullable=False),
    sa.Column('about', sa.String(length=45), nullable=True),
    sa.Column('photoUrl', sa.String(length=10000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_category', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicad')
    op.drop_table('localad')
    op.drop_table('user')
    op.drop_table('location')
    op.drop_table('category')
    # ### end Alembic commands ###
